### PR TITLE
How Virtual Environment Works

### PR DESCRIPTION
**Pull request by jianshen92**

### CODE REVIEW

**Review by keatmin — DISMISSED** [review]
LGTM!

**Comment by keatmin** [comment]
@jianshen92 since it's a daily gotchas, should we do date as the header `venv.md` gotcha?

**Comment by jianshen92** [comment]
> Well then again, venv is not really daily

how do we define daily then?

**Comment by keatmin** [comment]
> > Well then again, venv is not really daily
> 
> how do we define daily then?

Sorry rephrased. I think I am just interested to tie a gotcha to a date so you know sort of the things you've learnt over time haha

**Review by keatmin — APPROVED** [review]
LGTM!

**Pull request merged**
